In [1]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [2]:
#preprocess
name = ["Age", "Education", "HusbandEducation", "Children", "Religion",
            "Working", "HusbandOccupation", "StandardLiving", "MediaExposure", "Contraceptive"]
dataset = pd.read_csv("cmc.data", names = name)
dataset

Age  Education  HusbandEducation  Children  Religion  Working  \
0      24          2                 3         3         1        1   
1      45          1                 3        10         1        1   
2      43          2                 3         7         1        1   
3      42          3                 2         9         1        1   
4      36          3                 3         8         1        1   
...   ...        ...               ...       ...       ...      ...   
1468   33          4                 4         2         1        0   
1469   33          4                 4         3         1        1   
1470   39          3                 3         8         1        0   
1471   33          3                 3         4         1        0   
1472   17          3                 3         1         1        1   

      HusbandOccupation  StandardLiving  MediaExposure  Contraceptive  
0                     2               3              0              1  
1                     3               4              0              1  
2                     3               4              0              1  
3                     3               3              0              1  
4                     3               2              0              1  
...                 ...             ...            ...            ...  
1468                  2               4              0              3  
1469                  1               4              0              3  
1470                  1               4              0              3  
1471                  2               2              0              3  
1472                  2               4              0              3  

[1473 rows x 10 columns]

In [3]:
dataArr = dataset.values
data = dataArr[:,0:9]  #data
label = dataArr[:,9]    # target

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data, label, test_size=0.2)

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
# k = 1
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

In [7]:
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

[[63 15 37]
 [24 27 22]
 [37 26 44]]
Accuracy: 0.4542372881355932


In [8]:
# k = 3
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

In [9]:
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

[[80  5 30]
 [32 19 22]
 [47 22 38]]
Accuracy: 0.46440677966101696


In [10]:
# k = 5
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

In [11]:
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

[[76 10 29]
 [25 25 23]
 [41 24 42]]
Accuracy: 0.4847457627118644


In [12]:
knn = KNeighborsClassifier(n_neighbors=5, weights="distance")
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

In [13]:
print(confusion_matrix(y_test, y_pred))
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

[[72 11 32]
 [24 26 23]
 [36 27 44]]
Accuracy: 0.48135593220338985
