In [1]:
import pandas as pd
import numpy as np

In [2]:
!dir

 Volume in drive F has no label.
 Volume Serial Number is 56FE-0272

 Directory of F:\ai

01/08/2020  01:28 AM    <DIR>          .
01/08/2020  01:28 AM    <DIR>          ..
01/08/2020  12:47 AM    <DIR>          .ipynb_checkpoints
01/08/2020  12:53 AM            30,961 cmc.data
01/08/2020  12:54 AM             2,054 cmc.names
01/08/2020  01:28 AM            14,128 Untitled.ipynb
               3 File(s)         47,143 bytes
               3 Dir(s)  404,197,478,400 bytes free


In [3]:
name = ["Age", "Education", "HusbandEducation", "Children", "Religion",
            "Working", "HusbandOccupation", "StandardLiving", "MediaExposure", "Contraceptive"]

In [4]:
name

['Age',
 'Education',
 'HusbandEducation',
 'Children',
 'Religion',
 'Working',
 'HusbandOccupation',
 'StandardLiving',
 'MediaExposure',
 'Contraceptive']

In [5]:
dataset = pd.read_csv("cmc.data", names = name)

In [6]:
dataset

Age  Education  HusbandEducation  Children  Religion  Working  \
0      24          2                 3         3         1        1   
1      45          1                 3        10         1        1   
2      43          2                 3         7         1        1   
3      42          3                 2         9         1        1   
4      36          3                 3         8         1        1   
...   ...        ...               ...       ...       ...      ...   
1468   33          4                 4         2         1        0   
1469   33          4                 4         3         1        1   
1470   39          3                 3         8         1        0   
1471   33          3                 3         4         1        0   
1472   17          3                 3         1         1        1   

      HusbandOccupation  StandardLiving  MediaExposure  Contraceptive  
0                     2               3              0              1  
1                     3               4              0              1  
2                     3               4              0              1  
3                     3               3              0              1  
4                     3               2              0              1  
...                 ...             ...            ...            ...  
1468                  2               4              0              3  
1469                  1               4              0              3  
1470                  1               4              0              3  
1471                  2               2              0              3  
1472                  2               4              0              3  

[1473 rows x 10 columns]

In [7]:
dataArr = dataset.values
dataArr

array([[24,  2,  3, ...,  3,  0,  1],
       [45,  1,  3, ...,  4,  0,  1],
       [43,  2,  3, ...,  4,  0,  1],
       ...,
       [39,  3,  3, ...,  4,  0,  3],
       [33,  3,  3, ...,  2,  0,  3],
       [17,  3,  3, ...,  4,  0,  3]], dtype=int64)

In [8]:
data = dataArr[:,0:9]  #data
label = dataArr[:,9]    # target

In [9]:
data

array([[24,  2,  3, ...,  2,  3,  0],
       [45,  1,  3, ...,  3,  4,  0],
       [43,  2,  3, ...,  3,  4,  0],
       ...,
       [39,  3,  3, ...,  1,  4,  0],
       [33,  3,  3, ...,  2,  2,  0],
       [17,  3,  3, ...,  2,  4,  0]], dtype=int64)

In [10]:
label

array([1, 1, 1, ..., 3, 3, 3], dtype=int64)

In [33]:
from sklearn.naive_bayes import ComplementNB, GaussianNB, MultinomialNB, BernoulliNB
model = ComplementNB()
model2 = GaussianNB()
model3 = MultinomialNB()
model4 = BernoulliNB()

In [26]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

In [27]:
cross_val_predict(model, data, label, cv=10)

array([3, 3, 3, ..., 2, 2, 3], dtype=int64)

In [34]:
accuracy = cross_val_score(model, data, label, cv=10)
accuracy2 = cross_val_score(model2, data, label, cv=10)
accuracy3 = cross_val_score(model3, data, label, cv=10)
accuracy4 = cross_val_score(model4, data, label, cv=10)

In [23]:
accuracy

array([0.47651007, 0.50675676, 0.47297297, 0.59183673, 0.55102041,
       0.51020408, 0.51020408, 0.52380952, 0.46938776, 0.48630137])

In [24]:
max(accuracy)

0.5918367346938775

In [35]:
max(accuracy2)

0.5167785234899329

In [36]:
max(accuracy3)

0.5337837837837838

In [37]:
max(accuracy4)

0.5067567567567568